services:
  speedtest:
    image: ghcr.io/withawin/speedtest:latest
    container_name: gofive-internal-speedtest

    restart: unless-stopped

    environment:
      MODE: standalone

      # false = LibreSpeed Classic UI เดิม
      USE_NEW_DESIGN: "true"

      TELEMETRY: "false"
      DISABLE_IPINFO: "true"
      WEBPORT: "8080"

    ports:
      - "18080:8080"

    security_opt:
      - no-new-privileges:true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"